//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_StoredProcedure_create.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessInformation
    {
        public int ID { get; set; }
        public string Business_Type { get; set; }
        public string Business_Category { get; set; }
        public string Business_SubCategory { get; set; }
        public string Business_Name { get; set; }
        public string Owner_Name { get; set; }
        public string H_No { get; set; }
        public string Street { get; set; }
        public string Area { get; set; }
        public string Landmark { get; set; }
        public string Pincode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PAN { get; set; }
        public string GST_Number { get; set; }
        public string CIN { get; set; }
        public string Billing_Address { get; set; }
        public string Billing_Label { get; set; }
        public string Email { get; set; }
        public string Alternate_Email { get; set; }
        public string Mobile_Number { get; set; }
        public string Alternate_Mobile { get; set; }
        public string Authorized_Signature { get; set; }
        public string Description { get; set; }
    }
}
